# Path: src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useSSL=FALSE&useServerPrepStmts=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    #    password: jju_JM_601
    password: tang0793
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  jackson:
  #    default-property-inclusion: non_null
  redis:
    host: localhost
    port: 6379

server:
  port: 80
  servlet:
    context-path: /mall

mybatis-plus:
  type-aliases-package: com.example.mall.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config: # 数据源配置
      logic-delete-field: delFlag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

logging:
  level:
    com.example.canteenweb.mapper: DEBUG

